// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzDgmJI5n8xYsavBrRlTV3P_N0kLpKJmg',
    appId: '1:578470589709:web:049f4c294132790155ec44',
    messagingSenderId: '578470589709',
    projectId: 'lahgu-43b08',
    authDomain: 'lahgu-43b08.firebaseapp.com',
    storageBucket: 'lahgu-43b08.firebasestorage.app',
    measurementId: 'G-HR32MZJV97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADdAGz381aIF7DZv_5JLAYbtRy3i48Fo',
    appId: '1:578470589709:android:db4c6a6ce0d68df055ec44',
    messagingSenderId: '578470589709',
    projectId: 'lahgu-43b08',
    storageBucket: 'lahgu-43b08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUgUYZSP587OyZgVgdbmT0BaUaP6KfYL0',
    appId: '1:578470589709:ios:27c1d8329470f4f255ec44',
    messagingSenderId: '578470589709',
    projectId: 'lahgu-43b08',
    storageBucket: 'lahgu-43b08.firebasestorage.app',
    iosBundleId: 'com.example.autisense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUgUYZSP587OyZgVgdbmT0BaUaP6KfYL0',
    appId: '1:578470589709:ios:27c1d8329470f4f255ec44',
    messagingSenderId: '578470589709',
    projectId: 'lahgu-43b08',
    storageBucket: 'lahgu-43b08.firebasestorage.app',
    iosBundleId: 'com.example.autisense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzDgmJI5n8xYsavBrRlTV3P_N0kLpKJmg',
    appId: '1:578470589709:web:d18e97433836a3d255ec44',
    messagingSenderId: '578470589709',
    projectId: 'lahgu-43b08',
    authDomain: 'lahgu-43b08.firebaseapp.com',
    storageBucket: 'lahgu-43b08.firebasestorage.app',
    measurementId: 'G-L362GCGD2S',
  );
}
